version: "3.8"

services:
    backend:
        image: ghcr.io/appcd-dev/dogeapi/dogeapi:docker
        ports:
            - 8000:8000
        environment:
            - ENVIRONMENT=dev
            - TESTING=0
            - DATABASE_URL=sqlite:///test.db
            - SECRET_KEY=dev
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
