version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        #image: ghcr.io/appcd-dev/dogeapi/dogeapi:latest
        ports:
            - 8000:8000
        environment:
            - ENVIRONMENT=dev
            - TESTING=0
            - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/postgres
            #- DATABASE_URL=sqlite:////var/run/dogeapi/dogeapi.sqlite
            - SECRET_KEY=dev
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
            - S3_BUCKET_NAME=appcd-demo-dogeapi
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
        depends_on:
            - db
            - presign
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
    presign:
        build:
            context: ../DogeFlaskAPI
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
            - S3_BUCKET=appcd-demo-dogeapi

