version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./DogeAPI:/usr/src/app
        ports:
            - 8000:8000
        environment:
            - ENVIRONMENT=dev
            - TESTING=0
            - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/postgres
            - SECRET_KEY=dev
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
