# Overriding the securityContext as this application at the moment needs to be aboe to write to the filesystem
securityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
        type: RuntimeDefault

# Overriding the service to use an ALB ingress
ingress:
    enabled: true
    className: "alb"
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
    hosts:
        - paths:
            - path: /
              pathType: Prefix
    tls: []

# Overriding the resources to use Fargate
tolerations:
- key: "eks.amazonaws.com/compute-type"
  value: "fargate"
  effect: NoSchedule

# Overriding the environment variables to use sqlite
env:
- name: ENVIRONMENT
  value: dev
- name: TESTING
  value: "0"
- name: DATABASE_URL
  value: "sqlite:////var/run/dogeapi/dogeapi.sqlite"
- name: SECRET_KEY
  value: "dev"
- name: ACCESS_TOKEN_EXPIRE_MINUTES
  value: "30"

# Fargate doesn't support AppArmor
apparmorProfile: null
