image:
    repository: ghcr.io/appcd-dev/dogeapi/dogeapi
    pullPolicy: Always
    tag: latest
securityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
        type: RuntimeDefault
ingress:
    enabled: true
    className: "alb"
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
    hosts:
        - paths:
            - path: /
              pathType: Prefix
    tls: []
tolerations:
- key: "eks.amazonaws.com/compute-type"
  value: "fargate"
  effect: NoSchedule
env:
- name: ENVIRONMENT
  value: dev
- name: TESTING
  value: "0"
- name: DATABASE_URL
  value: "sqlite:////var/run/dogeapi/dogeapi.sqlite"
- name: SECRET_KEY
  value: "dev"
- name: ACCESS_TOKEN_EXPIRE_MINUTES
  value: "30"
