name: APPCD Diff check 
on:
  pull_request:
    branches:
      - main
jobs:
  compare-artifacts:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/appcd-dev/appcd-dist/appcd:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root --entrypoint /bin/bash --pull always
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main_branch
      - name: Generate IaC from Main Branch
        run: |
          appcd generate --mode ci --lang python --scanpath ./main_branch -o artifact/main/
      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: pr_branch
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=$(basename ${{ github.head_ref}})" >> $GITHUB_OUTPUT
      - name: echo branch name
        run: echo ${{ steps.extract_branch.outputs.branch }}
      - name: Generate IaC from PR branch
        run: |
          appcd generate --mode ci --lang python --scanpath ./main_branch -o artifact/${{ steps.extract_branch.outputs.branch }}/
      - name: Generate diff between Main and PR branch
        run: |
          mkdir -p pr_branch/deployment_files
          mv artifact/main/* pr_branch/deployment_files/
          cd pr_branch
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add deployment_files
          git commit -m "staging deployment files from main to compare them"
          rm -rf deployment_files/* 
          cd ..
          mv artifact/${{ steps.extract_branch.outputs.branch }}/* pr_branch/deployment_files/
          cd pr_branch
          git diff --output=../diff.txt deployment_files/ | cat
          cat ../diff.txt
      - name: Comment PR with IaC Changes
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('diff.txt', 'utf-8');
            const body = `### IaC Changes:\n\`\`\`${diff}\`\`\``;
            await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
            })
