name: Build and lint

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: pull latest
        run: make pull
      - name: Build image
        run: make build
      - name: Generate IAC for main branch
        env:
          APPCD_TOKEN: ${{ secrets.APPCD_TOKEN }}
          APPCD_URL: ${{ secrets.APPCD_URL }}
        uses: appcd-dev/action@v0.0.1
        with:
            cloud: 'aws'
            language: 'Python'
            outputDir: './.appcd/charts'
            scanPath: '.'
            targetCompute: 'k8s'
      