name: Deploy

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
      - cd

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Test AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: "2"
      - run: aws --version
        shell: bash
      - name: Get EKS kubeconfig
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws eks update-kubeconfig --name demo-demo --region us-east-2
      - name: Check Kubernetes context
        run: kubectl config get-contexts
      - name: Deploy Helm
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          helm upgrade demo-chart ./.appcd/charts/dogeapi --dry-run
