name: Deploy

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
      - cd

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: run appCD
        run: |
          docker run --rm --name iacgen \
          -v "$(pwd)/.appcd:/appcd" \
          ghcr.io/appcd-dev/iac-gen:main create \
          -m /appcd/manifest.json -d k8s -o /appcd/charts
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: "2"
      - name: Configure Kubernetes access
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-2
          aws eks update-kubeconfig --name demo-demo
      - name: Install Helm Diff
        run: |
          helm plugin install https://github.com/databus23/helm-diff
      - name: Helm diff
        run: |
          helm diff upgrade demo-chart ./.appcd/charts/dogeapi -f .appcd/overrides/dogeapi/values.yaml --install
      - name: Helm Upgrade
        run: |
          helm upgrade demo-chart ./.appcd/charts/dogeapi -f .appcd/overrides/dogeapi/values.yaml --install --dry-run
